[tool.poetry]
name = "crossmint-challenge"
version = "0.1.0"
description = "Megaverses are 2D spaces comprised of combinations of different astral objects: ğŸªPOLYanets with ğŸŒ™SOLoons around them and â˜„comETHs floating around."
authors = ["Wolfgang <wleon@bakrypt.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
